Apply Martinet's feedback
ETHTaipei/ETH-Taipei-Website pull request #184
Opened 2024-01-12 06:28 UTC by DylanYang0523

- [x] 2024 版本多加一個選項連到 2023
- [ ] 2023 版本上面多加一個連回 2024，然後讓 這是舊版本這件事情很明顯 (not sure how)
- [x] Speaker application 的按鈕可以移到最上面嗎？在下面好遠，最好是一打開網頁直接看到，要不就是馬上 scroll 就找到
可以加上 Sponsorship application的按鈕然後也跟. Speaker application的按鈕放在一起在最上面嗎？
- [x] "Welcome to the first ETHTaipei held in Taiwan." ==> "Welcome to ETHTaipei the 2024 edition!!!"
- [x] "We believe that ETHTaipei presents an unparalleled opportunity to learn about cutting-edge technology and applications about Ethereum" => "ETHTaipei presents an unparalleled opportunity to learn about cutting-edge technology and applications about Ethereum (check out our 2023 edition here!)" 然後把 here 連結到 2023版本的 agenda

2024-01-12 08:16 UTC, antoncoding approved these changes
Some wording suggestions

2024-01-12 08:16 UTC, antoncoding commented on public/constant/content.ts
> +    "In this unique opportunity, you can choose to be one of our compelling speakers and share your story, or become a supporter of our events and co-create an unforgettable experience. Whether you w
```suggestion
    "In this unique opportunity, you can choose to be one of our compelling speakers and share your expertise, or become a supporter of our events and co-create an unforgettable experience. Whether you want to take center stage or be in the background, this is your time to let your unique light shine. Join us and create the excitement and charm of the event together!",
```

2024-01-12 08:16 UTC, antoncoding commented on public/constant/content.ts
> +    "In this unique opportunity, you can choose to be one of our compelling speakers and share your story, or become a supporter of our events and co-create an unforgettable experience. Whether you w
This would makes it sound less like any "startup sharing conference" but a technical one

2024-01-12 08:16 UTC, antoncoding commented on public/constant/content.ts
> +  recapGoBackText: "Do you want to see more? Let's go back to ",
```suggestion
  recapGoBackText: "Want to see more detail? Let's go back to ",
```

2024-01-12 10:34 UTC, Ankarrr requested changes
> 就找到，可以加上 Sponsorship application的按鈕然後也跟. Speaker application的按鈕放在一起在最上面嗎？
> 目前作法：我加了一個區塊在 banner 之下，讓用戶可以申請。但不是到最上面，我想還是不要壓過主視覺為主，所以放在 banner 底下的第一區塊。如果還想再往上提，我建議可能是取代或是加在主視覺上的 "Conference" & "Hackthon" 這兩個地方，看大家覺得要再往上搬嗎？還是現在這樣排序就 OK？

這兩個 button 是目前最重要的 call to action，所以我認爲需要一進來就讓用戶看到！

我建議的解法是：
1. 加在主視覺上的 "Conference" & "Hackthon" 這兩個地方
2. 加在 navbar 上
3. 兩個都做

以上我都可以，看你覺得哪個解法比較好

2024-01-12 10:34 UTC, Ankarrr commented on components/HomePage/Recap.tsx
> +            ETH TPE 2023
EthTapiei 2023

2024-01-13 12:52 UTC, DylanYang0523 commented
更新：在 NAV & Banner 都加上按鈕導向 Apply 頁面。

2024-01-15 15:16 UTC, Ankarrr approved these changes

2024-01-15 23:04 UTC, merged